BE | GET therapist Profile
GSG-G13/ntherapy-express pull request #12
Opened 2023-06-15 08:37 UTC by YasserAmro0

- this Route should fetch data for specific therapist by **therapisID**
- If therapist not activated we should return back with no Therapist found
- check id is number 
- check therapist is Active or not

2023-06-15 09:10 UTC, MohannadSabaa approved these changes

2023-06-15 09:13 UTC, raghdarizq approved these changes

2023-06-15 09:16 UTC, LinaYahya requested changes

2023-06-15 09:16 UTC, LinaYahya commented on __tests__/therapist.ts
> +
why to delete index file, 
Instead we can tun `beforeAll` and `afterAll` at index and we can export all test suites at index as follows
```js
describe('therapist tests', therapistTest)
```

2023-06-15 09:16 UTC, LinaYahya commented on __tests__/therapist.ts
> +    it('should return 404 when invalid ID is provided', async () => {
add a test case for inactive therapists

2023-06-15 09:16 UTC, LinaYahya commented on src/app.ts
> +app.use('/api/v1', router);
why do you use `therapist` router instead of our main router,
So please restore index file at router folder and import all subroutes there

2023-06-15 09:16 UTC, LinaYahya commented on src/controllers/therapist.ts
> +interface TypeData extends TherapistAttributes {
move interface to `types` folder

2023-06-15 09:16 UTC, LinaYahya commented on src/controllers/therapist.ts
> +    if (!parseInt(id, 10)) {
why to try tp parse number to check if it's a number instead u can use `isNaN`

2023-06-15 09:16 UTC, LinaYahya commented on src/controllers/therapist.ts
> +      throw templateErrors.BAD_REQUEST('error id should be number');
```suggestion
      throw templateErrors.BAD_REQUEST('id should be number');

```

2023-06-15 09:16 UTC, LinaYahya commented on src/controllers/therapist.ts
> +        throw templateErrors.NOT_FOUND('therapist isActive is false');
```suggestion
        throw templateErrors.NOT_FOUND('therapist not found');

```
No need to provide extra information about user status

2023-06-15 09:16 UTC, LinaYahya commented on src/db/build.ts
> +  // process.exit();
```suggestion
```

2023-06-15 09:16 UTC, LinaYahya commented on src/routes/index.ts
> +
import all subroutes here and export route to use it in `app.ts`

2023-06-15 09:16 UTC, LinaYahya commented on src/services/therapistProfile.ts
> +// import { TherapistAttributes } from '../types';
```suggestion

```

2023-06-15 11:38 UTC, LinaYahya requested changes

2023-06-15 11:38 UTC, LinaYahya commented on src/controllers/therapist.ts
> +const therapistController = async (req: Request, res: Response, next: NextFunction) => {
```suggestion
const findTherapistById = async (req: Request, res: Response, next: NextFunction) => {

```

2023-06-15 11:38 UTC, LinaYahya commented on src/controllers/therapist.ts
> +import { TherapistWithOptional } from '../types';
```suggestion
import { TherapistWithUserOptional } from '../types';

```

2023-06-15 11:38 UTC, LinaYahya commented on src/services/index.ts
> +import Therapist from './therapistProfile';
```suggestion
import findTherapistService from './therapistProfile';

```

2023-06-15 11:38 UTC, LinaYahya commented on src/controllers/therapist.ts
> +    if (Number.isNaN(Number(id))) {
```suggestion
    if (Number.isNaN(id)) {

```

2023-06-16 14:10 UTC, LinaYahya approved these changes

2023-06-16 14:10 UTC, merged