build: make Therpists search
GSG-G13/ntherapy-express pull request #14
Opened 2023-06-15 08:53 UTC by raghdarizq

- this Route should fetch therapists
-  getAllTherapist: Search for a therapists by name and cheek if his active 
The code allows for searching therapists by name and implementing pagination to retrieve a specific number of therapists per page. If no name is provided in the query, it retrieves all therapists without any filtering.

2023-06-15 09:40 UTC, MohannadSabaa approved these changes

2023-06-15 09:40 UTC, LinaYahya requested changes
please check [this PR](https://github.com/GSG-G13/ntherapy-express/pull/12
) comments as well,
Also we have to start with offest `0`

2023-06-15 09:40 UTC, LinaYahya commented on src/app.ts
> +app.use(therapists);
Here we need to use our main Router, at `/router/index.ts` please import all subrouter and use it there

2023-06-15 09:40 UTC, LinaYahya commented on src/routes/therapists.ts
> +// http://localhost:8080/therapists?q=Al&page=0
```suggestion
```

2023-06-15 09:40 UTC, LinaYahya commented on src/services/therapists.ts
> +    attributes: ['profileImg', 'major', 'hourlyRate'],
we need to retrieve therapistID so we can redirect user to therapist profile

2023-06-15 09:40 UTC, LinaYahya commented on src/services/therapists.ts
> +const getAllTherapist = async (name: string, page: number, limit: number) => {
we don't neet to have limit here as a parameter, Insted let us import `Limit` and use it Here

2023-06-15 09:40 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    res.status(200).json(therapists);
```suggestion
    res.json(therapists);
```
The default status code going to be `200` So there is no need to specify it, as well as response payload doesn't follow what we agreed on

2023-06-15 09:40 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    if (!therapists.length) {
what if we have zero length therapist, What do u expect to happen,
Can u please trace the whole flow

2023-06-15 09:40 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    const limit = 8;
let us declare this at separate file at config folder, and please UPPERCASE it as this is a constant ,
```js
const THERAPISTS_LIMIT = 8;
```

2023-06-15 09:40 UTC, LinaYahya commented on src/controllers/therapists.ts
> +      res.status(204).json({});
```suggestion
      res.status(204).json({data: [], message: 'No therapist found'});
```

2023-06-15 09:40 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    const pageNumber = parseInt(page as string, 2) || 1;
can you please check having page as a string?
Can u please try to print pageNumber when page is `10` or `zero`

2023-06-15 10:03 UTC, ahmedmurtaja commented on __tests__/therapists.ts
> +import buildDB from "../src/db/build";
use SingleQoutes

2023-06-15 10:03 UTC, ahmedmurtaja commented on __tests__/therapists.ts
> +import dbConnection from "../src/db/connection";
use SingleQoutes

2023-06-16 17:20 UTC, YasserAmro0 approved these changes

2023-06-17 08:08 UTC, LinaYahya requested changes

2023-06-17 08:08 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    }
I guess no need to check therapists' length, SO if no therapists are found we'll end with empty array as a result, and no problem with that, while here we can't handle response as status `204` responded with no content, So I'll not be able to catch response result

2023-06-17 08:08 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    const therapists = await getAllTherapist(q as string || ' ', pageNumber, THERAPISTS_LIMIT);
```suggestion
    const therapists = await getAllTherapist(q as string || '', pageNumber, THERAPISTS_LIMIT);
```
Why to have default value as a space, replace it please with empty string

2023-06-17 08:08 UTC, LinaYahya commented on src/services/therapists.ts
> +    limit,
```suggestion
    limit: THERAPISTS_LIMIT,
```

2023-06-17 08:08 UTC, LinaYahya commented on src/db/connection.ts
> +export const THERAPISTS_LIMIT = 8;
please move this to config/constants.ts and import from there

2023-06-17 08:08 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    const therapists = await getAllTherapist(q as string || ' ', pageNumber, THERAPISTS_LIMIT);
```suggestion
    const therapists = await getAllTherapist(q as string || ' ', pageNumber);
```

2023-06-17 08:08 UTC, LinaYahya commented on src/controllers/therapists.ts
> +    const pageNumber = Number(page) || 1;
please check if the page is a number or not, If not responded with 400 bad request

2023-06-17 10:19 UTC, LinaYahya approved these changes

2023-06-17 10:37 UTC, ahmedmurtaja approved these changes

2023-06-17 11:34 UTC, merged