[NTH-86]  update isAvailable
GSG-G13/ntherapy-express pull request #17
Opened 2023-06-18 17:30 UTC by YasserAmro0

- A Route to Mark isAvailable as a true | false
- Therapist Protected Route

2023-06-18 17:54 UTC, ahmedmurtaja requested changes

2023-06-18 17:54 UTC, ahmedmurtaja commented on src/controllers/appointment.ts
> +  } catch (err: unknown) {
```suggestion
  } catch (err:) {

```
u can remove unknown from catch block

2023-06-18 17:54 UTC, ahmedmurtaja commented on src/controllers/appointment.ts
> +  } catch (error: unknown) {
same here

2023-06-19 03:16 UTC, ahmedmurtaja approved these changes

2023-06-19 08:10 UTC, LinaYahya approved these changes

2023-06-19 08:50 UTC, raghdarizq approved these changes

2023-06-19 08:50 UTC, merged