[NTH-74] - feat: nodmailer function added to services file
GSG-G13/ntherapy-express pull request #19
Opened 2023-06-19 07:31 UTC by MohannadSabaa

2023-06-19 08:50 UTC, raghdarizq approved these changes

2023-06-19 09:17 UTC, ahmedmurtaja requested changes

2023-06-19 09:17 UTC, ahmedmurtaja commented on src/services/nodemailer.ts
> +    port: 587,
no need to set the port to 587 since the default to 587 if is secure is false

2023-06-19 09:17 UTC, ahmedmurtaja commented on src/services/nodemailer.ts
> +const mailer = async (info: any) => {
```suggestion
const mailer = async (info:SendMailOptions) => {

```
remove any

2023-06-19 09:17 UTC, ahmedmurtaja commented on src/services/nodemailer.ts
> +const mailer = async (info: any) => {
`import nodemailer, { SendMailOptions } from 'nodemailer';
`

2023-06-19 09:50 UTC, ahmedmurtaja requested changes

2023-06-19 09:50 UTC, ahmedmurtaja commented on __tests__/appointment.ts
> +console.log(config.TOKEN_TEST_THERAPIST);
remove console.log

2023-06-20 10:36 UTC, LinaYahya approved these changes

2023-06-20 10:36 UTC, merged