[NTH-65] POST appointment
GSG-G13/ntherapy-express pull request #22
Opened 2023-06-20 09:17 UTC by ahmedmurtaja

2023-06-20 09:23 UTC, ahmedmurtaja commented on src/types/therapist.ts
> +  id: number;
when I removed the id, a database error occurred because of duplicate appointment pk, I will fix it tomorrow

2023-06-20 09:23 UTC, ahmedmurtaja commented on src/services/appointment.ts
> +          id: 21 + appointments.length + 1,
for now, until I solve the date problem, I don't want to think about the id problem, I will fix it later

2023-06-20 12:45 UTC, MohannadSabaa approved these changes

2023-06-22 03:28 UTC, raghdarizq approved these changes

2023-06-22 07:16 UTC, LinaYahya requested changes
@ahmedmurtaja 
Great Job Ahmed, small points to fix, and please add a timezone to our appointment datetime, And maybe some tests gonaa fail due to this change

2023-06-22 07:16 UTC, LinaYahya commented on src/db/build.ts
> +  await sequelize.sync({ force: true, alter: true });
```suggestion
  await sequelize.sync({ force: true});
```

2023-06-22 07:16 UTC, LinaYahya commented on src/services/appointment.ts
> +    updateOnDuplicate: ['id'],
```suggestion

```

2023-06-22 07:16 UTC, LinaYahya commented on src/services/appointment.ts
> +    const hourRange = moment.duration(1, 'hour');
```suggestion
    const ONE_RANGE_HOUR = moment.duration(1, 'hour');

```

2023-06-22 09:02 UTC, LinaYahya approved these changes

2023-06-22 11:15 UTC, YasserAmro0 approved these changes

2023-06-22 11:17 UTC, merged