server to send Client Secret  for payment
GSG-G13/ntherapy-express pull request #24
Opened 2023-06-21 19:35 UTC by YasserAmro0

router findClientSecret gets ClientSecret and sends it to the front to handle page payment

2023-06-21 19:59 UTC, ahmedmurtaja requested changes
Great Job Yasser

2023-06-21 19:59 UTC, ahmedmurtaja commented on src/services/payment.ts
> +  apiVersion: '2022-11-15',
why do we need to specify the version?
```suggestion

```

2023-06-22 03:27 UTC, raghdarizq approved these changes

2023-06-22 11:35 UTC, LinaYahya requested changes

2023-06-22 11:35 UTC, LinaYahya commented on src/controllers/payment.ts
> +    return res.send({
```suggestion
    return res.json({

```

2023-06-22 11:35 UTC, LinaYahya commented on src/routes/index.ts
> +router.post('/create-payment-intent', findClientSecret);
```suggestion
router.post('/payment-intent', findClientSecret);
```

2023-06-22 11:35 UTC, LinaYahya commented on src/routes/index.ts
> +router.post('/create-payment-intent', findClientSecret);
can we create this route as a user protected route, So we can get user email to send

2023-06-22 11:35 UTC, LinaYahya commented on src/services/payment.ts
> +const calculateOrderAmount = () => 1400;
we need to get  session price as well from the client side

2023-06-22 11:35 UTC, LinaYahya commented on src/services/payment.ts
> +    payment_method_types: ['card'],
```suggestion
    payment_method_types: ['card'],
        receipt_email, //user email from user data (userId)

```

2023-06-23 15:27 UTC, MohannadSabaa approved these changes

2023-06-25 08:32 UTC, LinaYahya approved these changes
Well Done @YasserAmro0

2023-06-25 09:24 UTC, ahmedmurtaja commented on src/controllers/payment.ts
> +import getClientSecret from '../services/payment';
import from index

2023-06-25 10:01 UTC, ahmedmurtaja approved these changes
good job

2023-06-25 10:12 UTC, merged