[NTH-67] create BookedAppointment
GSG-G13/ntherapy-express pull request #26
Opened 2023-06-22 13:21 UTC by raghdarizq

This task is a controller function that handles the creation of a new session. It receives a POST request through the Express framework and requires the user role privilege. It uses several third-party components such as "RequestWithUserRole," "AppointmentWithTherapistOptional," "generateMeeting," "templateErrors," "BookedAppointment," and "User." The main steps in the task include checking the availability of the requested appointment and the user's existence. If the appointment and user exist, the appointment is marked as booked. Then, it retrieves the therapist's email and the user's email. Using the "generateMeeting" function, it generates a meeting using the appointment's details. Finally, it returns a JSON response with a success message and the user's email.

2023-06-22 13:31 UTC, ahmedmurtaja approved these changes

2023-06-22 13:31 UTC, ahmedmurtaja commented on .vscode/settings.json
> +  "cSpell.words": [
remove this from the settings
just keep this lines 
```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
  
  ```

2023-06-22 17:43 UTC, ahmedmurtaja requested changes

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
Amazing Raghda, there is too much code in the controller file I think it would be cleaner if we put it in the services file

For example we can move  ``sequalize`` stuff  into a service

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      throw templateErrors.UNAUTHORIZED('user not found');
I don't understand why you check if user data is not found since we already check for it in the checkAuth middleware before entering this route

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      throw templateErrors.BAD_REQUEST('The Therapist email is not available');
how it's possible not to find the therapist's email if it likely it will be a server error not a bad request

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +
```suggestion
    const userId = userData?.userId;
```

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      where: { id: userData.userId },
i added suggestion to use 
```js   
 const therapistId = userData?.therapistId;
```
instead of accessing userId like this

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      throw templateErrors.BAD_REQUEST('The Therapist email is not available');
```suggestion
      throw templateErrors.BAD_REQUEST('Something went wrong,The user email is not available);
```
Same here it's not a bad request that we can't find user's email

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      throw templateErrors.BAD_REQUEST('The Therapist email is not available');
we can create custom error with 500 status

2023-06-22 17:43 UTC, ahmedmurtaja commented on src/controllers/session.ts
> +      userEmail,
why send a user email in the response?

2023-06-23 15:13 UTC, MohannadSabaa approved these changes

2023-06-25 08:19 UTC, LinaYahya approved these changes

2023-06-25 08:19 UTC, LinaYahya commented on src/services/session.ts
> +const bookedAppointment = async (appointmentId: number) => {
Still not renamed, `bookAppointment`

2023-06-25 08:35 UTC, YasserAmro0 approved these changes

2023-06-25 09:52 UTC, ahmedmurtaja approved these changes

2023-06-25 09:54 UTC, merged