Nth 85
GSG-G13/ntherapy-express pull request #28
Opened 2023-06-25 08:58 UTC by raghdarizq

2023-06-25 10:13 UTC, LinaYahya requested changes

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +      throw templateErrors.NOT_FOUND('user not found');
```suggestion
      throw templateErrors.BAD_REQUEST('wrong email or password');
```

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +    if (!user) {
please do check user is active

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +    next(err);
handle validation error please

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +      throw templateErrors.UNAUTHORIZED('The password is invalid');
```suggestion
      throw templateErrors.BAD_REQUEST('wrong email or password');
```

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +    const token = jwt.sign({ email: user.email }, config.SECRET_KEY, { expiresIn: '1h' });
please use sign async instead of blocking code using synchronous methods

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +    const token = jwt.sign({ email: user.email }, config.SECRET_KEY, { expiresIn: '1h' });
and please follow our agreed payload to sign token [Authentication middleware](https://www.notion.so/BE-Authentication-middleware-9d8f274a43d440cfb7dbeb0e8384b741?pvs=4)

2023-06-25 10:13 UTC, LinaYahya commented on src/routes/userLogin.ts
> +// router.post('/', checkAuth(RolesForSelect.therapist), userLoginController);
remove comments

2023-06-25 10:13 UTC, LinaYahya commented on src/routes/userLogin.ts
> +router.post('/', userLoginController);
```suggestion
router.post('/login', login);
```

2023-06-25 10:13 UTC, LinaYahya commented on src/routes/index.ts
> +router.use('/userLogin', userRouter);
```suggestion
router.use('/auth', userRouter);
```

2023-06-25 10:13 UTC, LinaYahya commented on src/controllers/userLogin.ts
> +dotenv.config();
```suggestion
```

2023-06-25 10:13 UTC, LinaYahya commented on src/helpers/validation/userLogin.ts
> +  password: Yup.string().required('Password is required'),
please do validate password

2023-06-25 15:00 UTC, ahmedmurtaja approved these changes

2023-06-26 08:28 UTC, MohannadSabaa approved these changes

2023-06-26 08:28 UTC, YasserAmro0 approved these changes

2023-06-26 08:59 UTC, LinaYahya requested changes

2023-06-26 08:59 UTC, LinaYahya commented on src/controllers/auth.ts
> +    const payload: {
```suggestion
    const payload: IPayload
```

2023-06-26 08:59 UTC, LinaYahya commented on src/controllers/auth.ts
> +      user,
```suggestion
      data: {access_token: token},
```

2023-06-26 08:59 UTC, LinaYahya commented on src/controllers/auth.ts
> +interface TherapistAndUser extends UsersAttributes {
please move this to types folder

2023-06-26 09:25 UTC, LinaYahya approved these changes

2023-06-26 09:35 UTC, merged