[NTH-90]
GSG-G13/ntherapy-express pull request #38
Opened 2023-06-30 15:11 UTC by raghdarizq

2023-07-01 09:30 UTC, LinaYahya requested changes

2023-07-01 09:30 UTC, LinaYahya commented on src/routes/auth.ts
> +router.get('/login', checkToken(), getAuth);
```suggestion
router.get('/', checkToken(), getAuth);
```

2023-07-01 09:30 UTC, LinaYahya commented on src/middlewares/checkToken.ts
> +const checkTokenForLogin = () => async (
```suggestion
const checkTokenForLogin = async (
```
No need to declare a function that return express middleware, we did that in checkAuth cause we need to call it with different roles
 ```js
 checkAuth('therapist');
checkAuth('user');
```
and checkAuth was a function that return a middleware, But here we can do the follow
```js
const checkToken = (req, res, next) => {}
// and call it 
route(checkToken, ourController)
```

2023-07-01 09:30 UTC, LinaYahya commented on src/middlewares/checkToken.ts
> +const checkTokenForLogin = () => async (
please rename it

2023-07-01 09:30 UTC, LinaYahya commented on src/middlewares/checkToken.ts
> +const checkTokenForLogin = () => async (
can we move this to same file of checkauth?

2023-07-01 09:30 UTC, LinaYahya commented on src/controllers/auth.ts
> +  if (req.user?.role === 'therapist') {
```suggestion
  if (req.user?.role === RolesForSelected.therapist) {
```

2023-07-01 09:30 UTC, LinaYahya commented on src/controllers/auth.ts
> +  try {
why not wrapping the whole controller with try, and please move to a service

2023-07-02 06:28 UTC, LinaYahya commented on src/middlewares/checkauth.ts
> +import { verifyToken } from '../helpers/jwt';
please import from helpers index file

2023-07-02 07:05 UTC, LinaYahya approved these changes

2023-07-02 07:49 UTC, MohannadSabaa approved these changes

2023-07-02 08:33 UTC, YasserAmro0 approved these changes

2023-07-02 08:41 UTC, ahmedmurtaja approved these changes

2023-07-02 11:07 UTC, LinaYahya approved these changes

2023-07-02 11:08 UTC, merged