feat(database): create db table Appointments
GSG-G13/ntherapy-express pull request #8
Opened 2023-06-11 13:45 UTC by YasserAmro0

2023-06-11 13:46 UTC, ahmedmurtaja commented on src/models/appointment.ts
> +import { AppointmentsAttributes } from '../types/index';
no need to  type index
```suggestion
import { AppointmentsAttributes } from '../types';
```

2023-06-11 13:48 UTC, ahmedmurtaja approved these changes

2023-06-11 13:50 UTC, LinaYahya requested changes

2023-06-11 13:50 UTC, LinaYahya commented on src/models/appointment.ts
> +import { AppointmentsAttributes } from '../types/index';
```suggestion
import { AppointmentsAttributes } from '../types/';
```

2023-06-11 13:50 UTC, LinaYahya commented on src/models/appointment.ts
> +const Appointment = sequelize.define<AppointmentsAttributes>('Appointment', {
```suggestion
const Appointment = sequelize.define<AppointmentsAttributes>('appointment', {
```

2023-06-11 13:50 UTC, LinaYahya commented on src/models/appointment.ts
> +    type: DataTypes.BOOLEAN,
let us add a default value as `false`

2023-06-12 07:35 UTC, ahmedmurtaja approved these changes

2023-06-12 10:06 UTC, LinaYahya requested changes

2023-06-12 11:07 UTC, LinaYahya approved these changes

2023-06-12 11:34 UTC, raghdarizq approved these changes

2023-06-12 11:39 UTC, MohannadSabaa approved these changes

2023-06-12 11:48 UTC, merged